# permissions for end users to edit fibers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fiber-editor-role
rules:
- apiGroups:
  - thecores.thrimbda.com
  resources:
  - fibers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - thecores.thrimbda.com
  resources:
  - fibers/status
  verbs:
  - get
