# permissions for end users to view fibers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fiber-viewer-role
rules:
- apiGroups:
  - thecores.thrimbda.com
  resources:
  - fibers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - thecores.thrimbda.com
  resources:
  - fibers/status
  verbs:
  - get
